'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabaseApi} from './session';
import {Plus,Search,X,RefreshCcw,Printer} from 'lucide-react';
import PassportScan from './passport';
import WhatsAppAction from './whatsapp';
export type OpSection='Pilgrims'|'Bookings'|'Visa cases'|'Tickets';
type Item=Record<string,any>;
const localDay=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const cash=(n:number)=>new Intl.NumberFormat('en-PK',{style:'currency',currency:'PKR',maximumFractionDigits:0}).format(n);
const clean=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const tables:Record<OpSection,string>={'Pilgrims':'krn_pilgrims','Bookings':'krn_bookings','Visa cases':'krn_visa_cases','Tickets':'krn_tickets'};
const statuses:Record<'Bookings'|'Visa cases',string[]>={'Bookings':['enquiry','confirmed','in_process','completed','cancelled'],'Visa cases':['draft','submitted','in_review','approved','rejected','cancelled']};
export default function OperationsWorkspace({section,token,endpoint,anonKey,onInvite}:{section:OpSection;token:string;endpoint:string;anonKey:string;onInvite:(kind:'pilgrim'|'agent',id:string)=>void}){
 const [data,setData]=useState<Record<string,Item[]>>({krn_pilgrims:[],krn_agents:[],krn_packages:[],krn_travel_groups:[],krn_bookings:[],krn_visa_cases:[],krn_tickets:[],krn_suppliers:[]});
 const [notice,setNotice]=useState<{phone?:string;agentPhone?:string;message:string;pilgrimId?:string}|null>(null);
 const [loading,setLoading]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState(false),[query,setQuery]=useState(''),[form,setForm]=useState<Record<string,string>>({}),[view,setView]=useState<Item|null>(null);
 const api=(path:string,options:RequestInit={})=>supabaseApi(endpoint,anonKey,path,options);
 const fetchAll=async(table:string)=>{let rows:Item[]=[];for(let i=0;;i+=500){const page=await api(`/rest/v1/${table}?select=*&order=created_at.desc&limit=500&offset=${i}`);rows=rows.concat(page);if(page.length<500)break}return rows};
 const load=async()=>{setLoading(true);setError('');try{const names=Object.keys(data);const sets=await Promise.all(names.map(fetchAll));setData(Object.fromEntries(names.map((n,i)=>[n,sets[i]])))}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[token]);
 const pilgrims=data.krn_pilgrims,agents=data.krn_agents,packages=data.krn_packages,groups=data.krn_travel_groups,bookings=data.krn_bookings,visas=data.krn_visa_cases,tickets=data.krn_tickets;
 const named=(table:string,id:string|null)=>id?data[table]?.find(x=>x.id===id)?.full_name||data[table]?.find(x=>x.id===id)?.name||id:'—';
 const bookingName=(id:string|null)=>id?bookings.find(x=>x.id===id)?.booking_reference||id:'—';
 const occupied=(id:string)=>bookings.filter(b=>b.group_id===id&&['confirmed','in_process','completed'].includes(b.status)).reduce((sum,b)=>sum+Number(b.quantity||1),0);
 const filtered=useMemo(()=>data[tables[section]].filter(r=>Object.values(r).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase()))),[data,section,query]);
 const put=(key:string,value:string)=>setForm(prev=>({...prev,[key]:value}));
 const formBookingChange=(id:string)=>{const b=bookings.find(x=>x.id===id);const pilgrim=pilgrims.find(x=>x.id===b?.pilgrim_id);setForm(prev=>({...prev,booking_id:id,bill_separately:id?'no':'yes',pilgrim_id:b?.pilgrim_id||prev.pilgrim_id||'',agent_id:b?.agent_id||pilgrim?.agent_id||prev.agent_id||'',bill_to:b?.bill_to||'pilgrim',quantity:String(b?.quantity||prev.quantity||1),countries:Array.isArray(b?.countries)?b.countries.join(','):prev.countries||'',origin:b?.origin||prev.origin||'',destination:b?.destination||prev.destination||'',flight_number:b?.flight_number||prev.flight_number||'',airline:b?.airline||prev.airline||'',passenger_name:pilgrim?.full_name||prev.passenger_name||'',ticket_type:b?.group_id?'group':'individual',visa_type:b?.group_id?'group':'individual'}))};
 const priceValue=(kind:'sale'|'cost',pkrField:string)=>{const usd=Number(form[`${kind}_usd`]||0);const rate=Number(form[kind==='sale'?'usd_rate':'cost_rate']||0);const quantity=Number(form.quantity||1);return Math.round(quantity*(usd>0?usd*rate:Number(form[pkrField]||0))*100)/100};
 const chargeFields=()=>({sale_usd:Number(form.sale_usd||0),usd_rate:Number(form.usd_rate||0),sale_unit_pkr:Number(form.sale_usd||0)>0?0:Number(form.sale_amount||0),sale_amount:priceValue('sale','sale_amount'),cost_usd:Number(form.cost_usd||0),cost_rate:Number(form.cost_rate||0),cost_unit_pkr:Number(form.cost_usd||0)>0?0:Number(form.cost_amount||0),cost_amount:priceValue('cost','cost_amount'),quantity:Number(form.quantity||1),agent_id:form.agent_id||null,bill_to:form.bill_to||'pilgrim',supplier_id:form.supplier_id||null,bill_separately:form.bill_separately==='yes'});
 const priceInputs=(kind:'sale'|'cost',pkrField:string,title:string)=>{const usd=Number(form[`${kind}_usd`]||0);const rateKey=kind==='sale'?'usd_rate':'cost_rate';return <div className="price-inputs"><h3>{title}</h3><label>USD per person / item<input type="number" min="0" step="0.01" value={form[`${kind}_usd`]||''} onChange={e=>put(`${kind}_usd`,e.target.value)}/></label><label>USD to PKR rate<input type="number" min="0" step="0.0001" required={usd>0} value={form[rateKey]||''} onChange={e=>put(rateKey,e.target.value)}/></label><label>PKR per person / item<input type="number" min="0" step="0.01" value={usd>0?String(Math.round(usd*Number(form[rateKey]||0)*100)/100):form[pkrField]||''} readOnly={usd>0} onChange={e=>put(pkrField,e.target.value)}/></label><strong className="price-total">{form.quantity||'1'} × unit price = {cash(priceValue(kind,pkrField))}</strong></div>};
 const countries=['Iran','Iraq','Syria','Saudi Arabia'];
 const selectedCountries=(form.countries||'').split(',').filter(Boolean);
 const countryPicker=<div className="country-picker"><strong>Visa countries</strong><label><input type="checkbox" checked={selectedCountries.length===countries.length} onChange={e=>put('countries',e.target.checked?countries.join(','):'')}/> Select all</label>{countries.map(c=><label key={c}><input type="checkbox" checked={selectedCountries.includes(c)} onChange={e=>put('countries',e.target.checked?[...selectedCountries,c].join(','):selectedCountries.filter(x=>x!==c).join(','))}/> {c}</label>)}</div>;
 const supplierOptions=data.krn_suppliers.map(x=>({id:x.id,name:`${x.name} · ${x.supplier_type}`}));
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{if((section==='Visa cases'||section==='Bookings'&&form.booking_kind==='visa')&&!selectedCountries.length)throw new Error('Select at least one visa country.');if(!Number.isInteger(Number(form.quantity||1))||Number(form.quantity||1)<1)throw new Error('Quantity must be a positive whole number.');let body:Item={};if(section==='Pilgrims')body={full_name:form.full_name?.trim(),passport_number:form.passport_number?.trim().toUpperCase(),father_name:form.father_name?.trim()||null,national_id:form.national_id?.trim()||null,passport_issue:form.passport_issue||null,address:form.address?.trim()||null,email:form.email?.trim()||null,nationality:form.nationality?.trim()||null,date_of_birth:form.date_of_birth||null,passport_expiry:form.passport_expiry||null,phone:form.phone?.trim()||null,agent_id:form.agent_id||null};
 if(section==='Bookings')body={pilgrim_id:form.pilgrim_id,agent_id:form.agent_id||null,package_id:form.package_id||null,group_id:form.group_id||null,booking_kind:form.booking_kind||'package',countries:selectedCountries,origin:form.origin?.trim()||null,destination:form.destination?.trim()||null,airline:form.airline?.trim()||null,flight_number:form.flight_number?.trim()||null,quantity:Number(form.quantity||1),sale_usd:Number(form.sale_usd||0),usd_rate:Number(form.usd_rate||0),unit_price_pkr:Number(form.sale_usd||0)>0?0:Number(form.total_amount||0),total_amount:priceValue('sale','total_amount'),bill_to:form.bill_to||'pilgrim',status:form.status||'enquiry'};
 if(section==='Visa cases')body={pilgrim_id:form.pilgrim_id,booking_id:form.booking_id||null,country:selectedCountries[0]||form.country,countries:selectedCountries,visa_type:form.visa_type,status:'draft',submission_date:form.submission_date||null,reference_number:form.reference_number?.trim()||null,...chargeFields()};
 if(section==='Tickets')body={booking_id:form.booking_id||null,pilgrim_id:form.pilgrim_id||null,origin:form.origin?.trim()||null,destination:form.destination?.trim()||null,flight_number:form.flight_number?.trim()||null,passenger_name:form.passenger_name?.trim(),ticket_type:form.ticket_type,airline:form.airline?.trim()||null,pnr:form.pnr?.trim()||null,ticket_number:form.ticket_number?.trim()||null,departure_date:form.departure_date||null,...chargeFields()};
 const created=await api(`/rest/v1/${tables[section]}`,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});if(section==='Pilgrims')setNotice({phone:body.phone,message:`Welcome to Karwan Rahiyaan Noor. Your registration is complete. Portal: ${location.origin}`,pilgrimId:created?.[0]?.id});if(section==='Pilgrims'&&created?.[0]?.id&&body.email&&body.phone)void onInvite('pilgrim',created[0].id);if(section==='Bookings'){const person=pilgrims.find(p=>p.id===body.pilgrim_id);setNotice({phone:person?.phone,agentPhone:agents.find(a=>a.id===body.agent_id)?.phone,message:`Karwan Rahiyaan Noor: Booking ${created?.[0]?.booking_reference||''} has been recorded. Status: ${body.status}. Amount: ${cash(body.total_amount)}. Portal: ${location.origin}`})}setOpen(false);setForm({});await load()}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const updateStatus=async(row:Item,status:string)=>{setLoading(true);setError('');try{await api(`/rest/v1/${tables[section]}?id=eq.${encodeURIComponent(row.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status})});if(section==='Bookings'){const person=pilgrims.find(p=>p.id===row.pilgrim_id);setNotice({phone:person?.phone,agentPhone:agents.find(a=>a.id===row.agent_id)?.phone,message:`Karwan Rahiyaan Noor: Booking ${row.booking_reference} status is now ${status}. Portal: ${location.origin}`})}await load()}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
 const printBooking=(b:Item)=>{const w=window.open('','_blank','width=800,height=700');if(!w){setError('Allow pop-ups to print.');return}w.document.write(`<!doctype html><html><head><title>${clean(b.booking_reference)}</title><style>body{font:16px Arial;color:#173841;margin:50px}h1{font:30px Georgia}table{border-collapse:collapse;width:100%;margin-top:30px}td{padding:13px;border-bottom:1px solid #dae5e4}td:last-child{text-align:right;font-weight:bold}</style></head><body><small>KARWAN RAHIYAAN NOOR PRIVATE LIMITED</small><h1>Booking summary</h1><p>${clean(b.booking_reference)}</p><table><tr><td>Pilgrim</td><td>${clean(named('krn_pilgrims',b.pilgrim_id))}</td></tr><tr><td>Package</td><td>${clean(named('krn_packages',b.package_id))}</td></tr><tr><td>Group</td><td>${clean(named('krn_travel_groups',b.group_id))}</td></tr><tr><td>Service</td><td>${clean(b.booking_kind||'package')}</td></tr><tr><td>Route / countries</td><td>${clean(b.booking_kind==='visa'?(b.countries||[]).join(', '):b.booking_kind==='ticket'?`${b.origin||''} to ${b.destination||''} · ${b.airline||''} ${b.flight_number||''}`:'—')}</td></tr><tr><td>Quantity</td><td>${clean(b.quantity||1)}</td></tr><tr><td>Status</td><td>${clean(b.status)}</td></tr><tr><td>Booking amount</td><td>${clean(cash(Number(b.total_amount)))}</td></tr></table><p>Payment and visa status are tracked separately. This summary is not a payment receipt.</p><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close()};
 const field=(key:string,label:string,type='text',required=false)=> <label key={key}>{label}<input type={type} required={required} min={type==='number'?'0':undefined} step={type==='number'?'0.01':undefined} value={form[key]||''} onChange={e=>put(key,e.target.value)}/></label>;
 const select=(key:string,label:string,choices:{id:string;name:string}[],required=false,onChange?:(v:string)=>void)=><label key={key}>{label}<select required={required} value={form[key]||''} onChange={e=>onChange?onChange(e.target.value):put(key,e.target.value)}><option value="">Select {label.toLowerCase()}</option>{choices.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
 const bookingOptions=bookings.filter(b=>!form.pilgrim_id||b.pilgrim_id===form.pilgrim_id).map(b=>({id:b.id,name:`${b.booking_reference} · ${named('krn_pilgrims',b.pilgrim_id)}`}));
 return <div className="operations"><div className="operation-actions"><div className="search"><Search size={18}/><input placeholder={`Search ${section.toLowerCase()}…`} value={query} onChange={e=>setQuery(e.target.value)}/></div><span>{filtered.length} records</span><button className="secondary" disabled={loading} onClick={load}><RefreshCcw size={16}/> Refresh</button><button className="primary add" onClick={()=>{setForm({status:'enquiry',submission_date:localDay(),quantity:'1',bill_separately:'yes',booking_kind:'package'});setError('');setOpen(true)}}><Plus size={18}/> New {section==='Visa cases'?'visa case':section.slice(0,-1).toLowerCase()}</button></div>{error&&<div className="error-banner">{error}</div>}{notice&&<div className="panel"><WhatsAppAction phone={notice.phone} message={notice.message} label="Send to pilgrim"/>{notice.agentPhone&&<WhatsAppAction phone={notice.agentPhone} message={notice.message} label="Send to agent"/>}{notice.pilgrimId&&<button className="secondary" onClick={()=>onInvite('pilgrim',notice.pilgrimId!)}>Create portal invitation</button>}</div>}
 <div className="panel operation-table"><div className="table-scroll"><table><thead><tr>{section==='Pilgrims'?<><th>Name</th><th>Passport</th><th>Agent</th><th>Expiry</th></>:section==='Bookings'?<><th>Reference</th><th>Pilgrim</th><th>Package</th><th>Group / seats</th><th>Service</th><th>Qty</th><th>Amount</th><th>Status</th></>:section==='Visa cases'?<><th>Pilgrim</th><th>Booking</th><th>Country</th><th>Visa type</th><th>Qty</th><th>Sale / cost</th><th>Status</th></>:<><th>Passenger</th><th>Booking</th><th>Airline</th><th>PNR</th><th>Flight / route</th><th>Qty</th><th>Sale / cost</th></>}<th>Details</th>{section==='Pilgrims'&&<th>Portal</th>}</tr></thead><tbody>{filtered.map(r=><tr key={r.id}>{section==='Pilgrims'?<><td>{r.full_name}</td><td>{r.passport_number}</td><td>{named('krn_agents',r.agent_id)}</td><td>{r.passport_expiry||'—'}</td></>:section==='Bookings'?<><td>{r.booking_reference}</td><td>{named('krn_pilgrims',r.pilgrim_id)}</td><td>{named('krn_packages',r.package_id)}</td><td>{named('krn_travel_groups',r.group_id)}{r.group_id&&<small className="cell-meta">{occupied(r.group_id)}/{groups.find(g=>g.id===r.group_id)?.capacity||'∞'} seats</small>}</td><td>{r.booking_kind==='visa'?(r.countries||[]).join(', '):r.booking_kind==='ticket'?[(r.origin||'?')+' → '+(r.destination||'?'),r.airline,r.flight_number].filter(Boolean).join(' · '):'Package'}</td><td>{r.quantity||1}</td><td>{cash(Number(r.total_amount))}</td><td><select value={r.status} disabled={loading} onChange={e=>updateStatus(r,e.target.value)}>{statuses.Bookings.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></td></>:section==='Visa cases'?<><td>{named('krn_pilgrims',r.pilgrim_id)}</td><td>{bookingName(r.booking_id)}</td><td>{(r.countries?.length?r.countries:[r.country]).join(', ')}</td><td>{r.visa_type}</td><td>{r.quantity||1}</td><td>{cash(Number(r.sale_amount||0))} / {cash(Number(r.cost_amount||0))}</td><td><select value={r.status} disabled={loading} onChange={e=>updateStatus(r,e.target.value)}>{statuses['Visa cases'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></td></>:<><td>{r.passenger_name}</td><td>{bookingName(r.booking_id)}</td><td>{r.airline||'—'}</td><td>{r.pnr||'—'}</td><td>{[r.airline,r.flight_number,(r.origin||'?')+' → '+(r.destination||'?')].filter(Boolean).join(' · ')}</td><td>{r.quantity||1}</td><td>{cash(Number(r.sale_amount||0))} / {cash(Number(r.cost_amount||0))}</td></>}<td><button className="link-button" onClick={()=>setView(r)}>View</button></td>{section==='Pilgrims'&&<td><button className="link-button" onClick={()=>onInvite('pilgrim',r.id)}>Create invite</button></td>}</tr>)}</tbody></table>{!loading&&!filtered.length&&<p className="finance-empty">No records found. Use New to add the first one.</p>}{loading&&<p className="finance-empty">Loading…</p>}</div></div>
 {open&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="modal"><div className="modal-head"><div><p className="eyebrow">NEW RECORD</p><h2>{section==='Bookings'?'Create booking':section==='Visa cases'?'New visa case':section==='Tickets'?'Issue ticket':'Register pilgrim'}</h2></div><button onClick={()=>setOpen(false)}><X size={20}/></button></div><form onSubmit={submit}><div className="fields">{section==='Pilgrims'&&<><PassportScan onExtract={values=>setForm(prev=>({...prev,...values}))}/>{field('full_name','Full name','text',true)}{field('passport_number','Passport number','text',true)}{field('father_name','Father name')}{field('national_id','National ID / CNIC')}{field('nationality','Nationality')}{field('date_of_birth','Date of birth','date')}{field('passport_issue','Passport issue date','date')}{field('passport_expiry','Passport expiry','date')}{field('address','Address')}{field('phone','Mobile / WhatsApp')}{field('email','Email','email')}{select('agent_id','Agent (optional)',agents.map(x=>({id:x.id,name:x.name})))}</>}
 {section==='Bookings'&&<>
 <label>Booking type<select value={form.booking_kind||'package'} onChange={e=>put('booking_kind',e.target.value)}><option value="package">Package</option><option value="visa">Visa</option><option value="ticket">Airline ticket</option></select></label>
 {select('pilgrim_id','Pilgrim',pilgrims.map(x=>({id:x.id,name:x.full_name+' · '+x.passport_number})),true,v=>setForm(prev=>({...prev,pilgrim_id:v,agent_id:pilgrims.find(p=>p.id===v)?.agent_id||prev.agent_id||''})))}
 {select('agent_id','Agent (optional)',agents.map(x=>({id:x.id,name:x.name})))}
 {form.booking_kind==='package'&&select('package_id','Package',packages.map(x=>({id:x.id,name:x.name+' · '+cash(Number(x.selling_price))})),false,v=>{const p=packages.find(x=>x.id===v);setForm(prev=>({...prev,package_id:v,total_amount:p?String(p.selling_price):prev.total_amount}))})}
 {select('group_id','Group (optional)',groups.filter(g=>g.status!=='cancelled').map(g=>({id:g.id,name:g.name+' · '+occupied(g.id)+'/'+(g.capacity||'∞')+' seats reserved'})))}
 {form.booking_kind==='visa'&&countryPicker}
 {form.booking_kind==='ticket'&&<>{field('origin','From city / airport','text',true)}{field('destination','To city / airport','text',true)}{field('airline','Airline','text',true)}{field('flight_number','Flight number','text',true)}</>}
 {field('quantity',form.booking_kind==='visa'?'Total number of visas across selected countries':form.booking_kind==='ticket'?'Number of tickets':'Number of travellers','number',true)}
 {priceInputs('sale','total_amount','Booking sale price')}
 {form.agent_id&&<label>Bill to<select value={form.bill_to||'pilgrim'} onChange={e=>put('bill_to',e.target.value)}><option value="pilgrim">Pilgrim account</option><option value="agent">Agent account</option></select></label>}
 <label>Status<select value={form.status||'enquiry'} onChange={e=>put('status',e.target.value)}>{statuses.Bookings.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><p className="form-help">Quantity × unit price is the total invoice. Enquiries do not reserve group seats; confirmation checks the full quantity.</p></>}
 {section==='Visa cases'&&<>
 {select('pilgrim_id','Pilgrim',pilgrims.map(x=>({id:x.id,name:x.full_name})),true,v=>setForm(prev=>({...prev,pilgrim_id:v,agent_id:pilgrims.find(p=>p.id===v)?.agent_id||'',booking_id:''})))}
 {select('agent_id','Agent (optional)',agents.map(x=>({id:x.id,name:x.name})))}
 {select('booking_id','Booking (optional)',bookingOptions,false,formBookingChange)}
 {countryPicker}<label>Visa type<select required value={form.visa_type||''} onChange={e=>put('visa_type',e.target.value)}><option value="">Select type</option><option value="group">Group</option><option value="individual">Individual</option></select></label>
 {field('quantity','Total number of visas across selected countries','number',true)}{field('submission_date','Submission date','date')}{field('reference_number','Embassy reference')}
 {priceInputs('sale','sale_amount','Visa sale price')}{priceInputs('cost','cost_amount','Embassy / company cost')}{select('supplier_id','Embassy / company (required for cost)',supplierOptions)}
 {form.agent_id&&<label>Bill to<select value={form.bill_to||'pilgrim'} onChange={e=>put('bill_to',e.target.value)}><option value="pilgrim">Pilgrim account</option><option value="agent">Agent account</option></select></label>}
 <label>Bill sale separately? <select value={form.bill_separately||'yes'} onChange={e=>put('bill_separately',e.target.value)}><option value="yes">Yes, add customer invoice</option><option value="no">No, included in booking package</option></select></label></>}
 {section==='Tickets'&&<>
 {select('pilgrim_id','Pilgrim',pilgrims.map(x=>({id:x.id,name:x.full_name})),true,v=>setForm(prev=>({...prev,pilgrim_id:v,passenger_name:pilgrims.find(p=>p.id===v)?.full_name||'',agent_id:pilgrims.find(p=>p.id===v)?.agent_id||'',booking_id:''})))}
 {select('agent_id','Agent (optional)',agents.map(x=>({id:x.id,name:x.name})))}
 {select('booking_id','Booking (optional)',bookingOptions,false,formBookingChange)}
 {field('passenger_name','Lead passenger name','text',true)}<label>Ticket type<select required value={form.ticket_type||''} onChange={e=>put('ticket_type',e.target.value)}><option value="">Select type</option><option value="group">Group</option><option value="individual">Individual</option></select></label>
 {field('origin','From city / airport','text',true)}{field('destination','To city / airport','text',true)}{field('airline','Airline','text',true)}{field('flight_number','Flight number','text',true)}{field('quantity','Number of tickets','number',true)}
 {field('pnr','PNR')}{field('ticket_number','Ticket number')}{field('departure_date','Departure date','date')}
 {priceInputs('sale','sale_amount','Ticket sale price')}{priceInputs('cost','cost_amount','Airline cost')}{select('supplier_id','Airline supplier (required for cost)',supplierOptions)}
 {form.agent_id&&<label>Bill to<select value={form.bill_to||'pilgrim'} onChange={e=>put('bill_to',e.target.value)}><option value="pilgrim">Pilgrim account</option><option value="agent">Agent account</option></select></label>}
 <label>Bill sale separately? <select value={form.bill_separately||'yes'} onChange={e=>put('bill_separately',e.target.value)}><option value="yes">Yes, add customer invoice</option><option value="no">No, included in booking package</option></select></label></>}</div>{error&&<p className="error">{error}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={loading}>{loading?'Saving…':'Save record'}</button></div></form></div></div>}

 {view&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setView(null)}}><div className="modal"><div className="modal-head"><div><p className="eyebrow">RECORD DETAILS</p><h2>{section==='Bookings'?view.booking_reference:section==='Pilgrims'?view.full_name:section==='Tickets'?view.passenger_name:named('krn_pilgrims',view.pilgrim_id)}</h2></div><button onClick={()=>setView(null)}><X size={20}/></button></div><div className="details">{Object.entries(view).filter(([k])=>!['id','created_at'].includes(k)).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><b>{k==='pilgrim_id'?named('krn_pilgrims',v):k==='agent_id'?named('krn_agents',v):k==='package_id'?named('krn_packages',v):k==='group_id'?named('krn_travel_groups',v):k==='booking_id'?bookingName(v):String(v??'—')}</b></div>)}</div>{section==='Bookings'&&<><div className="related"><h3>Related records</h3><p>Visa cases: {visas.filter(v=>v.booking_id===view.id).length} · Tickets: {tickets.filter(t=>t.booking_id===view.id).length}</p><p>Payments and invoices are recorded separately in Ledger.</p></div><button className="secondary" onClick={()=>printBooking(view)}><Printer size={16}/> Print booking summary</button></>}</div></div>}
 </div>
}
