'use client';
import {useEffect,useState} from 'react';
import {supabaseApi} from './session';

type Item=Record<string,any>;
export default function Portal({kind,token,endpoint,anonKey,userId}:{kind:'pilgrim'|'agent';token:string;endpoint:string;anonKey:string;userId:string}){
 const [packages,setPackages]=useState<Item[]>([]),[bookingPilgrim,setBookingPilgrim]=useState(''),[bookingPackage,setBookingPackage]=useState(''),[bookingQuantity,setBookingQuantity]=useState(1),[posting,setPosting]=useState(false),[statusMessage,setStatusMessage]=useState(''); const [profile,setProfile]=useState<Item|null>(null),[pilgrims,setPilgrims]=useState<Item[]>([]),[bookings,setBookings]=useState<Item[]>([]),[entries,setEntries]=useState<Item[]>([]),[error,setError]=useState('');
 useEffect(()=>{let active=true;const load=async()=>{try{
  const table=kind==='agent'?'krn_agents':'krn_pilgrims';
  const mine=await supabaseApi(endpoint,anonKey,`/rest/v1/${table}?select=*&auth_user_id=eq.${userId}`);
  if(!mine[0])throw new Error('Your portal profile is not linked yet. Contact the office.');
  const people=kind==='agent'?await supabaseApi(endpoint,anonKey,'/rest/v1/krn_pilgrims?select=id,full_name,passport_number'):[mine[0]];
  const related=people.length?await supabaseApi(endpoint,anonKey,`/rest/v1/krn_bookings?select=*&pilgrim_id=in.(${people.map((p:Item)=>p.id).join(',')})&order=created_at.desc`):[];
  const ledger=await supabaseApi(endpoint,anonKey,`/rest/v1/krn_finance_entries?select=*&party_type=eq.${kind}&party_id=eq.${mine[0].id}&order=created_at.asc`);
  const catalog=await supabaseApi(endpoint,anonKey,'/rest/v1/rpc/krn_portal_packages',{method:'POST',body:'{}'});if(active){setProfile(mine[0]);setPilgrims(people);setBookings(related);setEntries(ledger);setPackages(catalog);setBookingPilgrim(people[0]?.id||'')}
 }catch(e){if(active)setError((e as Error).message)}};void load();return()=>{active=false}},[kind,token,endpoint,anonKey,userId]);
 const requestBooking=async(e:React.FormEvent)=>{e.preventDefault();setPosting(true);setStatusMessage('');try{const reference=await supabaseApi(endpoint,anonKey,'/rest/v1/rpc/krn_portal_create_booking_quantity',{method:'POST',body:JSON.stringify({p_pilgrim:bookingPilgrim,p_package:bookingPackage,p_quantity:bookingQuantity})});setStatusMessage(`Booking request ${reference} received. The office will confirm it.`);const updated=await supabaseApi(endpoint,anonKey,`/rest/v1/krn_bookings?select=*&pilgrim_id=in.(${pilgrims.map(p=>p.id).join(',')})&order=created_at.desc`);setBookings(updated);setBookingPackage('')}catch(err){setStatusMessage((err as Error).message)}finally{setPosting(false)}};
 const amount=(n:number)=>new Intl.NumberFormat('en-PK',{style:'currency',currency:'PKR',maximumFractionDigits:0}).format(n);
 const balance=entries.reduce((n,e)=>n+Number(e.amount)*(e.entry_type==='invoice'||e.entry_type==='supplier_bill'||e.entry_type==='refund'?1:e.entry_type==='receipt'||e.entry_type==='payment'?-1:0)*(e.reversal_of?-1:1),0);
 return <div className="content portal"><p className="eyebrow">{kind.toUpperCase()} PORTAL</p><h1>Welcome, {profile?.name||profile?.full_name||'traveller'}</h1><p className="muted">Your bookings and account statement</p>{error&&<div className="error-banner">{error}</div>}{!profile&&!error&&<p>Loading your records…</p>}{profile&&<><div className="stats"><div className="stat"><span>Bookings</span><strong>{bookings.length}</strong></div><div className="stat"><span>{kind==='agent'?'Pilgrims':'Passport'}</span><strong>{kind==='agent'?pilgrims.length:profile.passport_number}</strong></div><div className="stat"><span>Account balance</span><strong>{amount(balance)}</strong><small>Positive: amount due</small></div></div><section className="panel"><h2>Request a booking</h2><form onSubmit={requestBooking} className="portal-booking"><label>Pilgrim<select required value={bookingPilgrim} onChange={e=>setBookingPilgrim(e.target.value)}>{pilgrims.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label><label>Package<select required value={bookingPackage} onChange={e=>setBookingPackage(e.target.value)}><option value="">Select package</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name} · {amount(Number(p.selling_price))}</option>)}</select></label><label>Quantity<input type="number" min={1} max={200} step={1} value={bookingQuantity} onChange={e=>setBookingQuantity(Number(e.target.value))}/></label><button className="primary" disabled={posting||!pilgrims.length}>{posting?'Submitting…':'Send booking request'}</button></form>{statusMessage&&<p>{statusMessage}</p>}<small>The office will confirm your enquiry and group seat. Payment is recorded separately.</small></section><section className="panel"><h2>Bookings</h2><div className="table-scroll"><table><thead><tr><th>Reference</th><th>Pilgrim</th><th>Quantity</th><th>Status</th><th>Amount</th></tr></thead><tbody>{bookings.map(b=><tr key={b.id}><td>{b.booking_reference}</td><td>{pilgrims.find(p=>p.id===b.pilgrim_id)?.full_name||'—'}</td><td>{b.quantity||1}</td><td>{b.status}</td><td>{amount(Number(b.total_amount))}</td></tr>)}</tbody></table></div>{!bookings.length&&<p className="muted">No bookings yet. Contact the office to make a booking.</p>}</section><section className="panel"><h2>Account statement</h2><div className="table-scroll"><table><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{entries.map(e=><tr key={e.id}><td>{e.entry_date}</td><td>{e.entry_type}</td><td>{e.document_number||e.reference||'—'}</td><td>{amount(Number(e.amount))}</td></tr>)}</tbody></table></div>{!entries.length&&<p className="muted">No financial entries yet.</p>}</section></>}</div>;
}
